
// Objective-C API for talking to the following Go packages
//
//	github.com/arror/xray
//
// File is generated by gomobile bind. Do not edit.
#ifndef __XrayKit_FRAMEWORK_H__
#define __XrayKit_FRAMEWORK_H__

#include "Xray.objc.h"
#include "Universe.objc.h"

#endif
