// Objective-C API for talking to github.com/arror/xray Go package.
//   gobind -lang=objc github.com/arror/xray
//
// File is generated by gobind. Do not edit.

#ifndef __Xray_H__
#define __Xray_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class XrayInstance;
@protocol XrayClient;
@class XrayClient;
@protocol XrayEnvironment;
@class XrayEnvironment;
@protocol XrayOSLogger;
@class XrayOSLogger;

@protocol XrayClient <NSObject>
- (BOOL)onPrepare:(id<XrayEnvironment> _Nullable)env error:(NSError* _Nullable* _Nullable)error;
- (void)onServerRunning;
- (void)onTrafficUpdate:(int64_t)up down:(int64_t)down;
@end

@protocol XrayEnvironment <NSObject>
- (BOOL)reset:(NSError* _Nullable* _Nullable)error;
- (BOOL)set:(NSString* _Nullable)name value:(NSString* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
@end

@protocol XrayOSLogger <NSObject>
- (void)onAccessLog:(NSString* _Nullable)message;
- (void)onDNSLog:(NSString* _Nullable)message;
- (void)onGeneralMessage:(NSString* _Nullable)severity message:(NSString* _Nullable)message;
@end

@interface XrayInstance : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)run:(id<XrayClient> _Nullable)client error:(NSError* _Nullable* _Nullable)error;
- (void)stop;
@end

FOUNDATION_EXPORT void XrayRegisterOSLogger(id<XrayOSLogger> _Nullable logger);

@class XrayClient;

@class XrayEnvironment;

@class XrayOSLogger;

@interface XrayClient : NSObject <goSeqRefInterface, XrayClient> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)onPrepare:(id<XrayEnvironment> _Nullable)env error:(NSError* _Nullable* _Nullable)error;
- (void)onServerRunning;
- (void)onTrafficUpdate:(int64_t)up down:(int64_t)down;
@end

@interface XrayEnvironment : NSObject <goSeqRefInterface, XrayEnvironment> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)reset:(NSError* _Nullable* _Nullable)error;
- (BOOL)set:(NSString* _Nullable)name value:(NSString* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
@end

@interface XrayOSLogger : NSObject <goSeqRefInterface, XrayOSLogger> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onAccessLog:(NSString* _Nullable)message;
- (void)onDNSLog:(NSString* _Nullable)message;
- (void)onGeneralMessage:(NSString* _Nullable)severity message:(NSString* _Nullable)message;
@end

#endif
